version: "3"
services:
  graphql-api:
    container_name: graphql-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:secret_passw0rd@postgres:5432/database
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
  postgres:
    container_name: postgres
    image: postgres:12.8
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret_passw0rd
      POSTGRES_DB: database
