version: "3.8"
services:
  graphql-api:
    container_name: graphql-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .docker.env
    environment:
      DATABASE_URL: ${DB_URL}
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
  postgres:
    container_name: postgres
    image: postgres:12.8
    ports:
      - "5432:5432"
    restart: always
    env_file: .docker.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
